# Theme settings
doks:
    baseurl: "https://gchure.github.io/phd/"
    color_theme:  grey # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Andrew S. Mueller | PhD Thesis
            image:
    footer:
        content:
            logo:
                text: Andrew S. Mueller | PhD Thesis
                image:
            copyright: Copyright &copy; 2020. - Andrew S. Mueller <br>All rights reserved.
    google_analytics:
        tracking_code: UA-109526846-4 
    comments:
        disqus_forum_shortname: gchure-phd # Add your disqus forum shortname

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
jekyll_get:
  - data: github
    json: 'https://api.github.com/orgs/gchure/repos'
    cache: false

exclude: [ 'README.md', 'CHANGELOG.md', 'src/data/', 
           'vendor', 'phd', 'phd.egg-info', 'dst', 'vscode', '.bundle',
           '.jekyll-cache', '_plugins', '*.lua','*.pdf','*.svg','src/*/code',
           '*.py', '*.tex', '*.sh', 'Gemfile', '*.lock', 'Makefile',
           'presentation/']
permalink: /:title/
gems:
  - jekyll-numbered-headings
  - jekyll-pandoc-multiple-formats

markdown: Pandoc
pandoc:
    extensions:
    - mathjax
    skip:
      full: false
      posts: false
      categories: false     
    flags: >
     --default-image-extension=.png
     --dpi 300
     --filter pandoc-crossref
     --bibliography src/references.bib
     --metadata link-citations
---
