site_name: SNSPDs for Fun & Profit
dev_addr: 127.0.0.1:9254
site_dir: site_deploy
docs_dir: pandoc_site
  
theme:
  name: material
  logo: ./site_images/logo.svg
  favicon: ./site_images/favicon.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: ./pandoc_site/overrides
  features:
    - navigation.indexes
    - navigation.expand
        
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - footnotes
  - pymdownx.details
  - admonition

extra_css:
  - ./stylesheets/extra.css
  - ./stylesheets/tippy.css

  

plugins:
  - search
  - bibtex:
      bib_file: "./pandoc_site/references_cleaned.bib"
      csl_file: "./pandoc_site/styles/apa_md.csl"


# nav:
#   - index.md
  # - High Rate Entanglement:
  #   - hre/index.md
  #   - April 2022: hre/hre_april_2022.md
  #   - May 2022: hre/hre_may_2022.md
  #   - Ultra Long Distance Demos: hre/hre_ultra.md
  #   - Fast Entanglement Scans: hre/fast_ent_scans.md
  #   - Action Framework: hre/action_framework.md
  # - DDAQ Software: ddaq.md

# nav:
#   - index.md
#   - Low Dark Count Rate Detection:
#     - Introduction: chapter_01/section_02_introduction.md
#     - Hardware: chapter_01/section_03_hardware.md
#     - Model: chapter_01/section_04_model.md
#   - High Rate Pulse Position Modulation: chapter_02/section_02_abstract.md
#     - Introduction: chapter_02/section_03_introduction.md
#   - Time Walk and Jitter Correction: chapter_03/section_02_abstract.md
#     - Introduction: chapter_03/section_03_introduction.md
#     - Method: chapter_03/section_04_method.md
#     - Results: chapter_03/section_05_results.md
#     - Peacoq: chapter_03/section_06_peacoq.md
#     - Outlook: chapter_03/section_07_outlook.md
#   - High Rate Entanglement Generation: chapter_04/section_02_abstract.md
#     - Introduction: chapter_04/section_03_introduction.md

nav:
  - index.md
  - "Ch. 1: Low Dark Count Rate SNSPD":
    - chapter_01/index.md
    - Introduction: chapter_01/section_03_introduction.md
    - Hardware: chapter_01/section_04_hardware.md
    - Model: chapter_01/section_05_model.md
  - "Ch. 2: Time Walk Correction": 
    - chapter_02/index.md
    - Introduction: chapter_02/section_03_introduction.md
    - Method: chapter_02/section_04_method.md
    - Conclusion: chapter_02/section_05_conclusion.md
    - Peacoq: chapter_02/section_06_peacoq.md
    - Outlook: chapter_02/section_07_outlook.md
  - "Ch. 3: PPM & Photon Resolution": 
    - chapter_03/index.md
    - Introduction: chapter_03/section_03_introduction.md
    - Method: chapter_03/section_04_method.md
    - Results: chapter_03/section_05_results.md
    - Phased Locked Loop: chapter_03/section_06_phased_locked_loop.md
    - Outlook: chapter_03/section_07_outlook.md
  - "Ch. 4: High Rate Entanglement": 
    - chapter_04/index.md
    - Introduction: chapter_04/section_03_introduction.md
    - System & Results: chapter_04/section_04_system_results.md
  - "A1: Aph 138 Homework":
    - chapter_05/index.md
    - Aph 138 Homework: chapter_05/section_06_aph_hw.md
  - "A2: Software Tools":
    - Software Tools: chapter_06/section_05_software_operation.md
    - Cheat Sheet: chapter_06/section_08_cheat_sheet.md



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/es5/latest?tex-svg.js
  - javascripts/wiki_hover.js
  - javascripts/fix_footnotes.js
  - javascripts/load_bokeh.js

# using footnote technique from https://github.com/ObsidianPublisher/tooltips-internal-link