site_name: Quantum Measurements with SNSPDs
dev_addr: 127.0.0.1:9254
site_dir: site_deploy
docs_dir: site
  
theme:
  name: material
  logo: ./site_images/logo.svg
  favicon: ./site_images/favicon.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: ./site/overrides
  features:
    - navigation.indexes
        
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - footnotes

extra_css:
  - ./stylesheets/extra.css

plugins:
  - search
  - bibtex:
      bib_file: "./site/references.bib"
      # csl_file: "../site/styles/ieee.csl"


# nav:
#   - index.md
  # - High Rate Entanglement:
  #   - hre/index.md
  #   - April 2022: hre/hre_april_2022.md
  #   - May 2022: hre/hre_may_2022.md
  #   - Ultra Long Distance Demos: hre/hre_ultra.md
  #   - Fast Entanglement Scans: hre/fast_ent_scans.md
  #   - Action Framework: hre/action_framework.md
  # - DDAQ Software: ddaq.md

# nav:
#   - index.md
#   - Low Dark Count Rate Detection:
#     - Introduction: chapter_01/section_02_introduction.md
#     - Hardware: chapter_01/section_03_hardware.md
#     - Model: chapter_01/section_04_model.md
#   - High Rate Pulse Position Modulation: chapter_02/section_02_abstract.md
#     - Introduction: chapter_02/section_03_introduction.md
#   - Time Walk and Jitter Correction: chapter_03/section_02_abstract.md
#     - Introduction: chapter_03/section_03_introduction.md
#     - Method: chapter_03/section_04_method.md
#     - Results: chapter_03/section_05_results.md
#     - Peacoq: chapter_03/section_06_peacoq.md
#     - Outlook: chapter_03/section_07_outlook.md
#   - High Rate Entanglement Generation: chapter_04/section_02_abstract.md
#     - Introduction: chapter_04/section_03_introduction.md

nav:
  - index.md
  - Low Dark Count Rate Detection:
    - chapter_01/index.md
    - Introduction: chapter_01/section_03_introduction.md
    - Hardware: chapter_01/section_04_hardware.md
    - Model: chapter_01/section_05_model.md
  - High Rate Pulse Position Modulation: 
    - chapter_02/index.md
    - Introduction: chapter_02/section_03_introduction.md
  - Time Walk and Jitter Correction: 
    - chapter_03/index.md
    - Introduction: chapter_03/section_03_introduction.md
    - Method: chapter_03/section_04_method.md
    - Results: chapter_03/section_05_results.md
    - Peacoq: chapter_03/section_06_peacoq.md
    - Outlook: chapter_03/section_07_outlook.md
  - High Rate Entanglement Generation: 
    - chapter_04/index.md
    - Introduction: chapter_04/section_03_introduction.md



extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js