site_name: SNSPhD
dev_addr: 127.0.0.1:9254
site_dir: site_deploy
docs_dir: pandoc_site
  
theme:
  name: material
  logo: ./site_images/logo.svg
  favicon: ./site_images/favicon.png
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: ./pandoc_site/overrides
  features:
    # - navigation.instant
    # - content.action.edit
    # - content.action.view
    - navigation.tracking
    - navigation.footer
    # - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
        
markdown_extensions:
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
      auto_append:
        - ./pandoc_site/abbreviations.md
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
  - footnotes
  - pymdownx.details
  - admonition

extra_css:
  - ./stylesheets/extra.css
  - ./stylesheets/tippy.css
extra:
  generator: false

  

plugins:
  - search
  - bibtex:
      bib_file: "./pandoc_site/references_cleaned.bib"
      csl_file: "./pandoc_site/styles/apa_md.csl"


# nav:
#   - index.md
  # - High Rate Entanglement:
  #   - hre/index.md
  #   - April 2022: hre/hre_april_2022.md
  #   - May 2022: hre/hre_may_2022.md
  #   - Ultra Long Distance Demos: hre/hre_ultra.md
  #   - Fast Entanglement Scans: hre/fast_ent_scans.md
  #   - Action Framework: hre/action_framework.md
  # - DDAQ Software: ddaq.md

# nav:
#   - index.md
#   - Low Dark Count Rate Detection:
#     - Introduction: chapter_01/section_02_introduction.md
#     - Hardware: chapter_01/section_03_hardware.md
#     - Model: chapter_01/section_04_model.md
#   - High Rate Pulse Position Modulation: chapter_02/section_02_abstract.md
#     - Introduction: chapter_02/section_03_introduction.md
#   - Time Walk and Jitter Correction: chapter_03/section_02_abstract.md
#     - Introduction: chapter_03/section_03_introduction.md
#     - Method: chapter_03/section_04_method.md
#     - Results: chapter_03/section_05_results.md
#     - Peacoq: chapter_03/section_06_peacoq.md
#     - Outlook: chapter_03/section_07_outlook.md
#   - High Rate Entanglement Generation: chapter_04/section_02_abstract.md
#     - Introduction: chapter_04/section_03_introduction.md

# repository
repo_name: sansseriff/phd_thesis
repo_url: https://github.com/sansseriff/phd_thesis

nav:
  - index.md
  - published.md
  - "Ch. 1: Introduction":
    - chapter_01/index.md
    - SNSPD background: chapter_01/section_03_snspd_background.md
    - The Differential SNSPD: chapter_01/section_04_dtsnspd.md
    - Structure of this thesis: chapter_01/section_05_structure.md
  - "Ch. 2: Low Dark Count Rate SNSPD":
    - chapter_02/index.md
    - Introduction: chapter_02/section_03_introduction.md
    - Design & Use: chapter_02/section_04_design_and_use.md
    - Model & Results: chapter_02/section_05_model_and_results.md
    # - Extra: chapter_02/section_05_extra.md
  - "Ch. 3: Time Walk Correction": 
    - chapter_03/index.md
    - Introduction: chapter_03/section_03_introduction.md
    - Method: chapter_03/section_04_method.md
    - PEACOQ and 2D-Correction: chapter_03/section_05_peacoq_2nd_order.md
    - Extra: chapter_03/section_06_extra.md
    - Conclusion: chapter_03/section_07_conclusion.md
  - "Ch. 4: PPM & Photon Resolution": 
    - chapter_04/index.md
    - Introduction: chapter_04/section_03_introduction.md
    - Method: chapter_04/section_04_method.md
    - Results: chapter_04/section_05_results.md
    - Discussion: chapter_04/section_06_discussion.md
    - Extra: chapter_04/section_07_extra.md
  - "Ch. 5: High Rate Entanglement": 
    - chapter_05/index.md
    - Introduction: chapter_05/section_03_introduction.md
    - System & Results: chapter_05/section_04_system_results.md
    - Discussion: chapter_05/section_05_discussion.md
    - Modelling Details: chapter_05/section_06_modelling_details.md
    - Experiment Details: chapter_05/section_07_experiment_details.md
  - "Ch. 6: Conclusion":
    - chapter_06/index.md
    - Summary & Reflection: chapter_06/section_03_summary_and_reflection.md
    - Outlook: chapter_06/section_04_outlook.md
  - "A1: Aph 138 Homework":
    - chapter_07/index.md
  - "A2: Software Tools":
    - chapter_08/index.md
    - Experiment Control Software: chapter_08/section_04_experiment_control.md
    - Data Analysis Software: chapter_08/section_05_data_analysis_visualization.md
    - TOF Spectrometer: chapter_08/section_06_tof_spectrometer.md
    # - Cheat Sheet: chapter_08/section_08_cheat_sheet.md
  - "A3: Interferometer Imbalance Analysis":
    - chapter_09/index.md
  # - "A4: Extra [DELETE]":
  #   - Cheat Sheet: extra/section_01_cheat_sheet.md




extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/es5/latest?tex-svg.js
  - javascripts/wiki_hover.js
  - javascripts/fix_footnotes.js
  - javascripts/load_bokeh.js
  - javascripts/lightbox.js

# using footnote technique from https://github.com/ObsidianPublisher/tooltips-internal-link