name: thesis 
on:
  push:
    branches:
      - master 
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
      - run: sudo dpkg -i pandoc-2.19.2-1-amd64.deb
      - run: pip install uv
      - run: uv sync
      - run: uv run mkdocs gh-deploy --force